#!/bin/sh -x

. /variables.sh
. /functions.sh

echo "PLD New Rescue booting"

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

mount -t proc proc /proc
mount -t sysfs sysfs /sys

mkdir -p /root
mount -t tmpfs none /root

mkdir -p /.rcd/modules
mv *.sqf /.rcd/modules

mkdir -p /root/dev /root/proc /root/sys
cp -a /dev/* /root/dev
mount --bind /root/dev /dev

for dir in tmp run ; do
        mkdir -p /root/$dir
	mount --bind /root/$dir /$dir
done

modprobe loop

echo "Starting udevd"
mkdir -p /run/udev
udevd --daemon
udevadm trigger --type=subsystems --action=add
udevadm trigger --type=devices --action=add

echo "Waiting for udev to setlle"
udevadm settle

/sbin/blkid

modprobe squashfs
modprobe aufs

mount_aufs

for module in $modules ; do
    load_module "$module"
done

udevadm control --exit

for dir in tmp run dev ; do
    umount /$dir
done

rm /.rcd/modules/*

cd /root
mount --move . /
exec chroot . /sbin/init

# vi: ft=sh sw=4 sts=4 et
